# Tutorial 9: sqs all features (forward)

---

### Introduction

Hello, this notebook will show how to use sqs to perform further feature selection, as we found that most features are very highly correlated, therfore we would need to remove those using the tool that we mentioned above.

In [1]:
print(1)

1

first, let us call the data

In [2]:
%store -r df_input_RG
%store -r y_RG
%store -r df_RG

In [3]:
y_RG = y_RG.map({'S': 1, 'B': 0})

---

calling some packages

In [6]:
# Python packages 
import pandas as pd # for importing data into data frame format
import seaborn as sns # For drawing useful graphs, such as bar graphs
import numpy as np
import matplotlib.pyplot as plt

---

<b><i> Data splitting </i></b>

In [7]:
from sklearn.model_selection import train_test_split

Xtrain_finall, Xtest_finall, Ytrain_finall, Ytest_finall = train_test_split( df_input_RG, y_RG, test_size = 0.3, random_state=3, stratify=y_RG) # train and valid sets

Xtrain, Xtest, Ytrain, Ytest = train_test_split( Xtrain_finall, Ytrain_finall, test_size = 0.3, random_state=3, stratify=Ytrain_finall) # train and valid sets

In [8]:
print(Xtrain.shape)
print(Xtest.shape)

(275, 2074)
(118, 2074)

---

<b><i> get the best N features </i></b>

In [9]:
%store -r featImp_RG

In [10]:
arrimp = np.array(featImp_RG).mean(0)
sorted_idx = arrimp.argsort()
print(sorted_idx[-10:])

[1316 1284 1093 1290   60 1034 1068 1029 1070 1107]

In [17]:
cols_ordered = df_input_RG.columns[sorted_idx]
# cols_ordered = df_input_RG.columns[sorted_idx][-400:]

cols_ordered

Index([1924.752, 1979.115, 1892.438, 1919.053,  1961.15, 1916.216,  2031.85,
       1670.516, 1962.635,  2233.11,
       ...
       1445.173, 1419.847, 1285.394, 1424.528,  850.046, 1248.864, 1269.657,
       1245.863, 1270.902, 1294.379],
      dtype='object', length=2074)

---

In [18]:
Xtrain[cols_ordered]

,1924.752,1979.115,1892.438,1919.053,1961.150,1916.216,2031.850,1670.516,1962.635,2233.110,...,1445.173,1419.847,1285.394,1424.528,850.046,1248.864,1269.657,1245.863,1270.902,1294.379
44,-1.262660,-1.244932,-1.225221,-1.261046,-1.253218,-1.260546,-1.216589,-1.168698,-1.252788,-1.167451,...,-1.200121,-1.187941,-1.184098,-1.191771,-1.105883,-1.185328,-1.184500,-1.185632,-1.184575,-1.183201
195,0.029038,-0.062715,-0.105898,0.029082,-0.022015,0.023594,-0.192147,-0.815595,-0.025100,-0.406921,...,-0.374789,-0.397771,-0.973544,-0.386318,-0.960269,-0.975631,-0.975455,-0.975118,-0.975309,-0.972193
153,-1.182826,-1.165534,-1.148377,-1.181556,-1.175216,-1.182125,-1.136108,-0.948594,-1.174508,-1.083726,...,-1.077361,-1.066583,-0.933537,-1.072886,-1.054559,-0.935165,-0.936432,-0.935009,-0.936731,-0.930488
428,0.371475,0.409882,0.444525,0.373682,0.392535,0.376073,0.475385,0.848140,0.393460,0.622458,...,0.584107,0.607801,0.991264,0.597366,1.084171,0.993072,0.992722,0.992166,0.992922,0.986539
307,0.636889,0.660021,0.662517,0.636313,0.650785,0.638491,0.691558,0.868651,0.650799,0.775918,...,0.714676,0.721459,0.936847,0.717137,1.016063,0.938420,0.939431,0.939123,0.939351,0.933865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,-1.426483,-1.423111,-1.405101,-1.425129,-1.426492,-1.424248,-1.406980,-1.145146,-1.426616,-1.350443,...,-1.347510,-1.339234,-1.073865,-1.343608,-1.110433,-1.073058,-1.073298,-1.072917,-1.073716,-1.074169
288,1.253711,1.266522,1.269546,1.255453,1.258841,1.255065,1.276402,1.288133,1.259270,1.300473,...,1.296429,1.301937,1.266589,1.300555,1.230404,1.263158,1.264537,1.263018,1.264719,1.268620
494,0.890011,0.907269,0.885836,0.886149,0.900297,0.887002,0.924622,1.084560,0.900601,0.996119,...,0.870634,0.872324,1.137038,0.868412,1.107634,1.134909,1.137376,1.134889,1.137946,1.135481
465,0.555348,0.589756,0.610575,0.556191,0.573925,0.558025,0.645707,0.884115,0.575261,0.754087,...,0.725796,0.742219,0.930608,0.736838,1.080445,0.936175,0.934483,0.936023,0.933795,0.927645
164,-0.846783,-0.836575,-0.819368,-0.844526,-0.842634,-0.845141,-0.820247,-0.795115,-0.842113,-0.795215,...,-0.782852,-0.765806,-0.882053,-0.771193,-1.034962,-0.890669,-0.890639,-0.889766,-0.890246,-0.873703

### SQS

In [19]:
# explore the number of selected features for RFE
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.pipeline import Pipeline
from matplotlib import pyplot
from sklearn.linear_model import LogisticRegression

In [ ]:
# https://machinelearningmastery.com/rfe-feature-selection-in-python/
selected = []
imp_ind = []
imp_freq = []

for i in range(1, 51, 1):
    print(i)
    sfs = SequentialFeatureSelector(estimator=LogisticRegression(solver = 'newton-cg'), n_features_to_select=i, direction = 'forward')
    # fit sfs
    sfs.fit(Xtrain[cols_ordered].values, Ytrain)
    # summarize all features
    selected_feat = []
    for i in range(Xtrain[cols_ordered].shape[1]):
        if sfs.support_[i] == True:
            selected_feat.append(i)
            print('Column: %d, Selected %s,' % (i, sfs.support_[i]))
        
    # print()
    selected.append(selected_feat)
    
    result = list(set(imp_ind) ^ set(selected[-1]))
    imp_freq.extend(Xtrain[cols_ordered].columns[result])    
    imp_ind.extend(result)    
    
    print(selected[-1])
    print(result)
    print(imp_ind)
    print(imp_freq)
    print()

1
Column: 119, Selected True,
[119]
[119]
[119]
[1783.109]

2
Column: 119, Selected True,
Column: 668, Selected True,
[119, 668]
[668]
[119, 668]
[1783.109, 840.402]

3
Column: 119, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
[119, 335, 668]
[335]
[119, 668, 335]
[1783.109, 840.402, 1287.309]

4
Column: 119, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
[119, 335, 668, 677]
[677]
[119, 668, 335, 677]
[1783.109, 840.402, 1287.309, 1534.107]

5
Column: 119, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
[119, 335, 668, 677, 699]
[699]
[119, 668, 335, 677, 699]
[1783.109, 840.402, 1287.309, 1534.107, 838.5]

6
Column: 119, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[119, 335, 668, 677, 699, 1109]
[1109]
[119, 668, 335, 677, 699, 1109]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127]

7
Column: 34, Selected True,
Column: 119, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 119, 335, 668, 677, 699, 1109]
[34]
[119, 668, 335, 677, 699, 1109, 34]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55]

8
Column: 34, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 96, 119, 335, 668, 677, 699, 1109]
[96]
[119, 668, 335, 677, 699, 1109, 34, 96]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048]

9
Column: 34, Selected True,
Column: 63, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 96, 119, 335, 668, 677, 699, 1109]
[63]
[119, 668, 335, 677, 699, 1109, 34, 96, 63]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659]

10
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 96, 119, 335, 668, 677, 699, 1109]
[77]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159]

11
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 335, 668, 677, 699, 1109]
[89]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01]

12
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 169, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 169, 335, 668, 677, 699, 1109]
[169]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336]

13
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 335, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 169, 190, 335, 668, 677, 699, 1109]
[190]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55]

14
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 169, 190, 335, 384, 668, 677, 699, 1109]
[384]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604]

15
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 139, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 139, 169, 190, 335, 384, 668, 677, 699, 1109]
[139]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565]

16
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 139, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 139, 169, 190, 312, 335, 384, 668, 677, 699, 1109]
[312]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95]

17
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 139, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 139, 169, 190, 312, 335, 384, 472, 668, 677, 699, 1109]
[472]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471]

18
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 139, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 139, 169, 190, 251, 312, 335, 384, 472, 668, 677, 699, 1109]
[251]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335]

19
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 139, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 139, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[386]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114]

20
Column: 34, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 63, 77, 89, 96, 119, 139, 151, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[151]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386, 151]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114, 1319.41]

21
Column: 34, Selected True,
Column: 51, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 51, 63, 77, 89, 96, 119, 139, 151, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[51]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386, 151, 51]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114, 1319.41, 1547.845]

22
Column: 34, Selected True,
Column: 51, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 91, Selected True,
Column: 96, Selected True,
Column: 119, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 51, 63, 77, 89, 91, 96, 119, 139, 151, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[91]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386, 151, 51, 91]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114, 1319.41, 1547.845, 1581.843]

23
Column: 34, Selected True,
Column: 51, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 91, Selected True,
Column: 96, Selected True,
Column: 98, Selected True,
Column: 119, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 51, 63, 77, 89, 91, 96, 98, 119, 139, 151, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[98]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386, 151, 51, 91, 98]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114, 1319.41, 1547.845, 1581.843, 1558.077]

24
Column: 34, Selected True,
Column: 51, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 91, Selected True,
Column: 96, Selected True,
Column: 98, Selected True,
Column: 119, Selected True,
Column: 132, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 51, 63, 77, 89, 91, 96, 98, 119, 132, 139, 151, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[132]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386, 151, 51, 91, 98, 132]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114, 1319.41, 1547.845, 1581.843, 1558.077, 1001.406]

25
Column: 34, Selected True,
Column: 51, Selected True,
Column: 53, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 91, Selected True,
Column: 96, Selected True,
Column: 98, Selected True,
Column: 119, Selected True,
Column: 132, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 51, 53, 63, 77, 89, 91, 96, 98, 119, 132, 139, 151, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[53]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386, 151, 51, 91, 98, 132, 53]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114, 1319.41, 1547.845, 1581.843, 1558.077, 1001.406, 1099.042]

26
Column: 34, Selected True,
Column: 51, Selected True,
Column: 53, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 91, Selected True,
Column: 95, Selected True,
Column: 96, Selected True,
Column: 98, Selected True,
Column: 119, Selected True,
Column: 132, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 51, 53, 63, 77, 89, 91, 95, 96, 98, 119, 132, 139, 151, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[95]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386, 151, 51, 91, 98, 132, 53, 95]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114, 1319.41, 1547.845, 1581.843, 1558.077, 1001.406, 1099.042, 1179.009]

27
Column: 34, Selected True,
Column: 51, Selected True,
Column: 53, Selected True,
Column: 55, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 91, Selected True,
Column: 95, Selected True,
Column: 96, Selected True,
Column: 98, Selected True,
Column: 119, Selected True,
Column: 132, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 51, 53, 55, 63, 77, 89, 91, 95, 96, 98, 119, 132, 139, 151, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[55]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386, 151, 51, 91, 98, 132, 53, 95, 55]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114, 1319.41, 1547.845, 1581.843, 1558.077, 1001.406, 1099.042, 1179.009, 976.513]

28
Column: 34, Selected True,
Column: 37, Selected True,
Column: 51, Selected True,
Column: 53, Selected True,
Column: 55, Selected True,
Column: 63, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 91, Selected True,
Column: 95, Selected True,
Column: 96, Selected True,
Column: 98, Selected True,
Column: 119, Selected True,
Column: 132, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,
Column: 472, Selected True,
Column: 668, Selected True,
Column: 677, Selected True,
Column: 699, Selected True,
Column: 1109, Selected True,
[34, 37, 51, 53, 55, 63, 77, 89, 91, 95, 96, 98, 119, 132, 139, 151, 169, 190, 251, 312, 335, 384, 386, 472, 668, 677, 699, 1109]
[37]
[119, 668, 335, 677, 699, 1109, 34, 96, 63, 77, 89, 169, 190, 384, 139, 312, 472, 251, 386, 151, 51, 91, 98, 132, 53, 95, 55, 37]
[1783.109, 840.402, 1287.309, 1534.107, 838.5, 1141.127, 1551.55, 1733.048, 1564.659, 1574.159, 1028.01, 1033.336, 1566.55, 1565.604, 946.565, 1023.95, 1037.471, 1022.335, 1115.114, 1319.41, 1547.845, 1581.843, 1558.077, 1001.406, 1099.042, 1179.009, 976.513, 1664.083]

29
Column: 34, Selected True,
Column: 37, Selected True,
Column: 51, Selected True,
Column: 53, Selected True,
Column: 55, Selected True,
Column: 63, Selected True,
Column: 65, Selected True,
Column: 77, Selected True,
Column: 89, Selected True,
Column: 91, Selected True,
Column: 95, Selected True,
Column: 96, Selected True,
Column: 98, Selected True,
Column: 119, Selected True,
Column: 132, Selected True,
Column: 139, Selected True,
Column: 151, Selected True,
Column: 169, Selected True,
Column: 190, Selected True,
Column: 251, Selected True,
Column: 312, Selected True,
Column: 335, Selected True,
Column: 384, Selected True,
Column: 386, Selected True,

---

In [ ]:
print(len(selected ))
# selected.append(cols_ordered[-51:])
# selected.append(cols_ordered)

### LR

In [ ]:
lr = LogisticRegression()

In [ ]:
solvers = ['newton-cg', 'liblinear']
penalty = ['l2']
c_values = [1000, 100, 10, 1.0, 0.1, 0.01, 0.001]
lr_par = dict(solver=solvers,penalty=penalty,C=c_values)

In [ ]:
models = [[lr, 'lr', 14]]
par = [lr_par]

In [ ]:
from source.ml_acc import get_accuracy_ml

In [ ]:
num_ml_tools = len(par)
ml_dicts = {}

for m, par in zip(models, par):
    key0 = str(m[1])
    ml_dicts[key0] = {}
    for f in selected:
        print(cols_ordered[f])

        xtr =  Xtrain[cols_ordered].iloc[:, f]
        xte =  Xtest[cols_ordered].iloc[:, f]
        print(xtr)
        results = get_accuracy_ml (m[0], m[2], par, np.array(xtr), np.array(Ytrain), np.array(xte), np.array(Ytest)) # to get the accuracies for the ml model

        key = str(m[1])+","+str(len(f))
        ml_dicts[key0][key] = {}

        ml_dicts[key0][key]['tot_acc'] = results[0]
        ml_dicts[key0][key]['jack_train'] = results[1]
        ml_dicts[key0][key]['jack_test'] = results[2]

---

In [ ]:
import json

In [ ]:
with open('ml_rg_fs9.txt', 'w') as file:
     file.write(json.dumps(ml_dicts)) # use `json.loads` to do the reverse

In [ ]:
import json
with open('ml_rg_fs.txt') as f:
    data = f.read()
    
ml_dicts = json.loads(data)

with open('base_rg.txt') as f:
    data = f.read()
    
baseDict = json.loads(data)
baseDict['lr'].keys()

In [ ]:
print(baseDict['lr'].keys()    )
print(ml_dicts['lr'].keys()    )

In [ ]:
from source.calculate_jack import jack_SD # importing the baseline code from source.basline file

In [ ]:
arr_all = []
for m, d in zip (models, ml_dicts.keys()):
    acc_arr = [] 
    sd_arr = [] 

    # print(ml_dicts[d])
    for key in ml_dicts[d].keys():
        acc_arr.append(ml_dicts[d][key][ 'tot_acc' ]) # append total accuracy to an array
        sd_train = jack_SD(np.zeros( len(ml_dicts[d][key][ 'jack_train' ]) ), ml_dicts[d][key][ 'jack_train' ])[0]
        sd_test = jack_SD(np.zeros( len(ml_dicts[d][key][ 'jack_test' ]) ), ml_dicts[d][key][ 'jack_test' ])[0]
        sd = np.sqrt( np.array((sd_train**2)) + np.array((sd_test**2)))
        sd_arr.append(sd) # append sd_arr to an array
    arr_all.append([ list(ml_dicts[d].keys()), acc_arr, sd_arr])

In [ ]:
colors = ['blue', 'purple', 'green', 'orange', 'red', 'brown']
plt.figure(figsize=(15, 7))
plt.title( "Precision  for different features with the SD", fontweight ='bold', fontsize =12)
plt.xlabel("Features", fontweight ='bold', fontsize =12)
plt.ylabel("Precision", fontweight ='bold', fontsize =12)

count = 0
n = len(colors)-1

space = []
tickFeat = []

for result, model, color in zip(arr_all, models, colors):
    a = np.linspace(n*count, n*(1+count)-2,49)
    print(a)
    space.extend(a)
    tickFeat.extend(result[0])
    plt.errorbar( a, result[1], result[2], fmt='o', label =model[1], color = color)
    count += 1

plt.xticks(space, tickFeat, rotation = 'vertical',  fontsize =12)
plt.ylim(.2, 1)
plt.legend()

plt.show()

In [ ]:
arr_diff_all = []

for m, m_key in zip (models, ml_dicts.keys()):
    acc_diff_arr = [] 
    sd_diff_arr = [] 
    for f_key in ml_dicts[m_key].keys():
        value = f_key.split(',')
        acc_diff_arr.append( ml_dicts[m_key][f_key][ 'tot_acc' ] - baseDict['lr']['lr, all'][ 'tot_acc' ]  )

        sd_train = jack_SD( baseDict['lr']['lr, all'][ 'jack_train' ], ml_dicts[m_key][f_key]['jack_train'] )[0]
        sd_test = jack_SD(  baseDict['lr']['lr, all'][ 'jack_test' ],  ml_dicts[m_key][f_key]['jack_test']   )[0]

        sd = np.sqrt( np.array((sd_train**2)) + np.array((sd_test**2)))
        sd_diff_arr.append(sd) # append sd_arr to an array
    arr_diff_all.append([ list(ml_dicts[m_key].keys()), acc_diff_arr, sd_diff_arr])

In [ ]:
colors = ['blue', 'purple', 'green', 'orange', 'red', 'brown']
plt.figure(figsize=(15, 7))
plt.title( "Precision  differences for ML methods versus LR_all for feature setsD", fontweight ='bold', fontsize =12)
plt.xlabel("Features", fontweight ='bold', fontsize =12)
plt.ylabel("Precision  difference", fontweight ='bold', fontsize =12)

count = 0
n = len(colors)-0.5
space = []
tickFeat = []

for result, model, color in zip(arr_diff_all, models, colors):
    a = np.linspace(n*count, n*(1+count)-2,49)
    space.extend(a)
    tickFeat.extend(result[0])
    plt.errorbar( a, result[1], result[2], fmt='o', label =model[1], color = color)
    count += 1
    
plt.plot(np.array(space), np.zeros(49*1), color = 'Black')        
plt.xticks(space, tickFeat, rotation = 'vertical',  fontsize =12)
plt.ylim(-.5, 1)
plt.legend()

plt.show()