# Tutorial 9: SQS on all features, (Forward)

---

### Introduction

Hello, this notebook will show how to use sequential adding to perform further feature selection, as we found that most features are very highly correlated, therfore we would need to remove those using the tool that we mentioned above.

first, let us call the data

In [1]:
%store -r df_input_GD
%store -r y_GD
%store -r df_GD

In [2]:
y_GD = y_GD.map({'S': 1, 'B': 0})

---

calling some packages

In [3]:
# Python packages 
import pandas as pd # for importing data into data frame format
import seaborn as sns # For drawing useful graphs, such as bar graphs
import numpy as np
import matplotlib.pyplot as plt

---

<b><i> Data splitting </i></b>

In [6]:
from sklearn.model_selection import train_test_split

Xtrain_finall, Xtest_finall, Ytrain_finall, Ytest_finall = train_test_split( df_input_GD, y_GD, test_size = 0.3, random_state=3, stratify=y_GD) # train and valid sets

Xtrain, Xtest, Ytrain, Ytest = train_test_split( Xtrain_finall, Ytrain_finall, test_size = 0.3, random_state=3, stratify=Ytrain_finall) # train and valid sets

In [7]:
print(Xtrain.shape)
print(Xtest.shape)

(267, 2074)
(115, 2074)

---

<b><i> get the best N features </i></b>

In [8]:
%store -r featImp_GD

In [9]:
arrimp = np.array(featImp_GD).mean(0)
sorted_idx = arrimp.argsort()
print(sorted_idx[-10:])

[ 15 205 144 153  71 180 157  60  43  86]

In [10]:
# cols_ordered = df_input_GD.columns[sorted_idx][-400:]
cols_ordered = df_input_GD.columns[sorted_idx]

cols_ordered

Index([1346.127, 1376.867, 1366.706, 1338.483, 1367.427, 1361.681, 1363.113,
       1896.591, 1351.037, 1343.337,
       ...
        837.687,  892.475,  874.121,  876.781,  853.123,   884.86,  877.969,
        850.046,  845.334,  857.355],
      dtype='object', length=2074)

---

In [11]:
Xtrain[cols_ordered]

,1346.127,1376.867,1366.706,1338.483,1367.427,1361.681,1363.113,1896.591,1351.037,1343.337,...,837.687,892.475,874.121,876.781,853.123,884.860,877.969,850.046,845.334,857.355
390,0.819178,0.751795,0.786673,0.832418,0.784061,0.796084,0.793079,0.435873,0.811352,0.823202,...,1.073175,1.069444,1.074404,1.075410,1.070955,1.076398,1.077060,1.074658,1.069245,1.072751
387,1.181236,1.121173,1.156632,1.187846,1.155358,1.166458,1.161798,0.547112,1.176666,1.182726,...,1.083759,1.102652,1.095158,1.094740,1.084817,1.102318,1.097641,1.086728,1.086045,1.091894
82,-1.287090,-1.271850,-1.279841,-1.285430,-1.277478,-1.272694,-1.277527,-1.098119,-1.283778,-1.286905,...,-1.136482,-1.124357,-1.123132,-1.118182,-1.130941,-1.120571,-1.124837,-1.129967,-1.130318,-1.129509
231,-0.278311,-0.138970,-0.206292,-0.310614,-0.204626,-0.235667,-0.224186,-0.028220,-0.260685,-0.288605,...,-0.778319,-0.764354,-0.773417,-0.777017,-0.775705,-0.773266,-0.770768,-0.780913,-0.780160,-0.774863
92,-1.205885,-1.199726,-1.202068,-1.202928,-1.199729,-1.192474,-1.199141,-0.497322,-1.204339,-1.205979,...,-1.048097,-1.026964,-1.029220,-1.026552,-1.042397,-1.021666,-1.028401,-1.043967,-1.043051,-1.038386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,1.244945,1.235629,1.238994,1.247206,1.239679,1.245064,1.242797,1.443695,1.244023,1.245688,...,1.281657,1.297762,1.296778,1.295549,1.282159,1.303682,1.299027,1.291414,1.287327,1.289458
448,1.384405,1.283668,1.341355,1.400394,1.341260,1.365649,1.356304,0.475537,1.379197,1.390457,...,1.254540,1.267011,1.258393,1.258921,1.250997,1.270007,1.264604,1.258756,1.256321,1.263501
482,1.560189,1.544388,1.558920,1.559469,1.559708,1.566422,1.563121,1.077124,1.562534,1.560818,...,1.194408,1.250676,1.229010,1.226928,1.207834,1.235981,1.223055,1.206959,1.193134,1.213936
157,-0.920283,-0.803154,-0.871879,-0.934745,-0.870158,-0.893279,-0.885603,0.634215,-0.911457,-0.925406,...,-0.793903,-0.787831,-0.791210,-0.792472,-0.794232,-0.791893,-0.789546,-0.791827,-0.797612,-0.792672
406,1.227814,1.206234,1.217619,1.232451,1.217898,1.223921,1.222188,0.987584,1.227157,1.229987,...,1.201287,1.228076,1.223200,1.223895,1.208138,1.230895,1.224843,1.211547,1.212978,1.218836

### SFS

In [12]:
# explore the number of selected features for RFE
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.pipeline import Pipeline
from matplotlib import pyplot
from sklearn.linear_model import LogisticRegression

In [ ]:
# https://machinelearningmastery.com/rfe-feature-selection-in-python/
selected = []
imp_ind = []
imp_freq = []

for i in range(1, 51, 1):
    print(i)
    sfs = SequentialFeatureSelector(estimator=LogisticRegression(solver = 'newton-cg'), n_features_to_select=i, direction = 'forward')
    # fit sfs
    sfs.fit(Xtrain[cols_ordered].values, Ytrain)
    # summarize all features
    selected_feat = []
    for i in range(Xtrain[cols_ordered].shape[1]):
        if sfs.support_[i] == True:
            selected_feat.append(i)
            print('Column: %d, Selected %s,' % (i, sfs.support_[i]))
        
    # print()
    selected.append(selected_feat)
    
    result = list(set(imp_ind) ^ set(selected[-1]))
    imp_freq.extend(Xtrain[cols_ordered].columns[result])    
    imp_ind.extend(result)    
    
    print(selected[-1])
    print(result)
    print(imp_ind)
    print(imp_freq)
    print()

1
Column: 2039, Selected True,
[2039]
[2039]
[2039]
[1395.393]

2
Column: 1552, Selected True,
Column: 2039, Selected True,
[1552, 2039]
[1552]
[2039, 1552]
[1395.393, 2492.924]

3
Column: 141, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[141, 1552, 2039]
[141]
[2039, 1552, 141]
[1395.393, 2492.924, 868.847]

4
Column: 11, Selected True,
Column: 141, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[11, 141, 1552, 2039]
[11]
[2039, 1552, 141, 11]
[1395.393, 2492.924, 868.847, 1309.415]

5
Column: 11, Selected True,
Column: 19, Selected True,
Column: 141, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[11, 19, 141, 1552, 2039]
[19]
[2039, 1552, 141, 11, 19]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754]

6
Column: 11, Selected True,
Column: 19, Selected True,
Column: 41, Selected True,
Column: 141, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[11, 19, 41, 141, 1552, 2039]
[41]
[2039, 1552, 141, 11, 19, 41]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55]

7
Column: 11, Selected True,
Column: 19, Selected True,
Column: 32, Selected True,
Column: 41, Selected True,
Column: 141, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[11, 19, 32, 41, 141, 1552, 2039]
[32]
[2039, 1552, 141, 11, 19, 41, 32]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963]

8
Column: 11, Selected True,
Column: 19, Selected True,
Column: 32, Selected True,
Column: 41, Selected True,
Column: 141, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[11, 19, 32, 41, 141, 1349, 1552, 2039]
[1349]
[2039, 1552, 141, 11, 19, 41, 32, 1349]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09]

9
Column: 11, Selected True,
Column: 19, Selected True,
Column: 32, Selected True,
Column: 41, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[11, 19, 32, 41, 141, 224, 1349, 1552, 2039]
[224]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769]

10
Column: 11, Selected True,
Column: 19, Selected True,
Column: 32, Selected True,
Column: 41, Selected True,
Column: 85, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[11, 19, 32, 41, 85, 141, 224, 1349, 1552, 2039]
[85]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567]

11
Column: 0, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 32, Selected True,
Column: 41, Selected True,
Column: 85, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 11, 19, 32, 41, 85, 141, 224, 1349, 1552, 2039]
[0]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127]

12
Column: 0, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 41, Selected True,
Column: 85, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 11, 19, 22, 32, 41, 85, 141, 224, 1349, 1552, 2039]
[22]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231]

13
Column: 0, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 41, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 11, 19, 22, 32, 41, 85, 97, 141, 224, 1349, 1552, 2039]
[97]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65]

14
Column: 0, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 36, Selected True,
Column: 41, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 11, 19, 22, 32, 36, 41, 85, 97, 141, 224, 1349, 1552, 2039]
[36]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297]

15
Column: 0, Selected True,
Column: 1, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 36, Selected True,
Column: 41, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 11, 19, 22, 32, 36, 41, 85, 97, 141, 224, 1349, 1552, 2039]
[1]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867]

16
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 36, Selected True,
Column: 41, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 11, 19, 22, 32, 36, 41, 85, 97, 141, 224, 1349, 1552, 2039]
[2]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706]

17
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 4, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 36, Selected True,
Column: 41, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 4, 11, 19, 22, 32, 36, 41, 85, 97, 141, 224, 1349, 1552, 2039]
[4]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427]

18
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 4, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 41, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 4, 11, 19, 22, 32, 33, 36, 41, 85, 97, 141, 224, 1349, 1552, 2039]
[33]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564]

19
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 4, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 4, 11, 19, 22, 32, 33, 36, 41, 44, 85, 97, 141, 224, 1349, 1552, 2039]
[44]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774]

20
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 4, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 4, 11, 19, 22, 32, 33, 36, 37, 41, 44, 85, 97, 141, 224, 1349, 1552, 2039]
[37]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774, 1130.183]

21
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 4, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 3, 4, 11, 19, 22, 32, 33, 36, 37, 41, 44, 85, 97, 141, 224, 1349, 1552, 2039]
[3]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37, 3]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774, 1130.183, 1338.483]

22
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 4, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 40, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 3, 4, 11, 19, 22, 32, 33, 36, 37, 40, 41, 44, 85, 97, 141, 224, 1349, 1552, 2039]
[40]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37, 3, 40]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774, 1130.183, 1338.483, 1130.676]

23
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 4, Selected True,
Column: 5, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 40, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 3, 4, 5, 11, 19, 22, 32, 33, 36, 37, 40, 41, 44, 85, 97, 141, 224, 1349, 1552, 2039]
[5]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37, 3, 40, 5]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774, 1130.183, 1338.483, 1130.676, 1361.681]

24
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 4, Selected True,
Column: 5, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 40, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 46, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 3, 4, 5, 11, 19, 22, 32, 33, 36, 37, 40, 41, 44, 46, 85, 97, 141, 224, 1349, 1552, 2039]
[46]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37, 3, 40, 5, 46]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774, 1130.183, 1338.483, 1130.676, 1361.681, 2488.138]

25
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 4, Selected True,
Column: 5, Selected True,
Column: 9, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 40, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 46, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 3, 4, 5, 9, 11, 19, 22, 32, 33, 36, 37, 40, 41, 44, 46, 85, 97, 141, 224, 1349, 1552, 2039]
[9]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37, 3, 40, 5, 46, 9]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774, 1130.183, 1338.483, 1130.676, 1361.681, 2488.138, 1343.337]

26
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 4, Selected True,
Column: 5, Selected True,
Column: 9, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 40, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 46, Selected True,
Column: 48, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 3, 4, 5, 9, 11, 19, 22, 32, 33, 36, 37, 40, 41, 44, 46, 48, 85, 97, 141, 224, 1349, 1552, 2039]
[48]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37, 3, 40, 5, 46, 9, 48]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774, 1130.183, 1338.483, 1130.676, 1361.681, 2488.138, 1343.337, 1270.902]

27
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 4, Selected True,
Column: 5, Selected True,
Column: 9, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 40, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 46, Selected True,
Column: 48, Selected True,
Column: 58, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 3, 4, 5, 9, 11, 19, 22, 32, 33, 36, 37, 40, 41, 44, 46, 48, 58, 85, 97, 141, 224, 1349, 1552, 2039]
[58]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37, 3, 40, 5, 46, 9, 48, 58]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774, 1130.183, 1338.483, 1130.676, 1361.681, 2488.138, 1343.337, 1270.902, 965.961]

28
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 4, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 9, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 40, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 46, Selected True,
Column: 48, Selected True,
Column: 58, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 3, 4, 5, 6, 9, 11, 19, 22, 32, 33, 36, 37, 40, 41, 44, 46, 48, 58, 85, 97, 141, 224, 1349, 1552, 2039]
[6]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37, 3, 40, 5, 46, 9, 48, 58, 6]
[1395.393, 2492.924, 868.847, 1309.415, 1320.754, 1171.55, 923.963, 893.09, 1464.769, 1354.567, 1346.127, 1076.231, 1874.65, 911.297, 1376.867, 1366.706, 1367.427, 1850.564, 1217.774, 1130.183, 1338.483, 1130.676, 1361.681, 2488.138, 1343.337, 1270.902, 965.961, 1363.113]

29
Column: 0, Selected True,
Column: 1, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 4, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 9, Selected True,
Column: 11, Selected True,
Column: 19, Selected True,
Column: 22, Selected True,
Column: 26, Selected True,
Column: 32, Selected True,
Column: 33, Selected True,
Column: 36, Selected True,
Column: 37, Selected True,
Column: 40, Selected True,
Column: 41, Selected True,
Column: 44, Selected True,
Column: 46, Selected True,
Column: 48, Selected True,
Column: 58, Selected True,
Column: 85, Selected True,
Column: 97, Selected True,
Column: 141, Selected True,
Column: 224, Selected True,
Column: 1349, Selected True,
Column: 1552, Selected True,
Column: 2039, Selected True,
[0, 1, 2, 3, 4, 5, 6, 9, 11, 19, 22, 26, 32, 33, 36, 37, 40, 41, 44, 46, 48, 58, 85, 97, 141, 224, 1349, 1552, 2039]
[26]
[2039, 1552, 141, 11, 19, 41, 32, 1349, 224, 85, 0, 22, 97, 36, 1, 2, 4, 33, 44, 37, 3, 40, 5, 46, 9, 48, 58, 6, 26]

---

### LR

In [ ]:
lr = LogisticRegression()

In [ ]:
solvers = ['newton-cg', 'liblinear']
penalty = ['l2']
c_values = [1000, 100, 10, 1.0, 0.1, 0.01, 0.001]
lr_par = dict(solver=solvers,penalty=penalty,C=c_values)

In [ ]:
models = [[lr, 'lr', 14]]
par = [lr_par]

In [ ]:
from source.ml_acc import get_accuracy_ml

In [ ]:
num_ml_tools = len(par)
ml_dicts = {}

for m, par in zip(models, par):
    key0 = str(m[1])
    ml_dicts[key0] = {}
    for f in selected:
        print(cols_ordered[f])

        xtr =  Xtrain[cols_ordered].iloc[:, f]
        xte =  Xtest[cols_ordered].iloc[:, f]
        print(xtr)
        # results = get_accuracy_ml (m[0], m[2], par, np.array(xtr), np.array(Ytrain), np.array(xte), np.array(Ytest)) # to get the accuracies for the ml model
        results = get_accuracy_ml (m[0], m[2], par, np.array(xtr), np.array(Ytrain), np.array(xtr), np.array(Ytrain)) # to get the accuracies for the ml model
        

        key = str(m[1])+","+str(len(f))
        ml_dicts[key0][key] = {}

        ml_dicts[key0][key]['tot_acc'] = results[0]
        ml_dicts[key0][key]['jack_train'] = results[1]
        ml_dicts[key0][key]['jack_test'] = results[2]

---

In [ ]:
import json

In [ ]:
with open('ml_gd_fs9.txt', 'w') as file:
     file.write(json.dumps(ml_dicts)) # use `json.loads` to do the reverse

In [ ]:
import json
with open('ml_gd_fs9.txt') as f:
    data = f.read()
    
ml_dicts = json.loads(data)

with open('base_gd.txt') as f:
    data = f.read()
    
baseDict = json.loads(data)
baseDict['lr'].keys()

In [ ]:
print(baseDict['lr'].keys()    )
print(ml_dicts['lr'].keys()    )

In [ ]:
from source.calculate_jack import jack_SD # importing the baseline code from source.basline file

In [ ]:
arr_all = []
for m, d in zip (models, ml_dicts.keys()):
    acc_arr = [] 
    sd_arr = [] 

    # print(ml_dicts[d])
    for key in ml_dicts[d].keys():
        acc_arr.append(ml_dicts[d][key][ 'tot_acc' ]) # append total accuracy to an array
        sd_train = jack_SD(np.zeros( len(ml_dicts[d][key][ 'jack_train' ]) ), ml_dicts[d][key][ 'jack_train' ])[0]
        sd_test = jack_SD(np.zeros( len(ml_dicts[d][key][ 'jack_test' ]) ), ml_dicts[d][key][ 'jack_test' ])[0]
        sd = np.sqrt( np.array((sd_train**2)) + np.array((sd_test**2)))
        sd_arr.append(sd) # append sd_arr to an array
    arr_all.append([ list(ml_dicts[d].keys()), acc_arr, sd_arr])

In [ ]:
colors = ['blue', 'purple', 'green', 'orange', 'red', 'brown']
plt.figure(figsize=(15, 7))
plt.title( "Precision  for different features with the SD", fontweight ='bold', fontsize =12)
plt.xlabel("Features", fontweight ='bold', fontsize =12)
plt.ylabel("Precision", fontweight ='bold', fontsize =12)

count = 0
n = len(colors)-1

space = []
tickFeat = []

for result, model, color in zip(arr_all, models, colors):
    a = np.linspace(n*count, n*(1+count)-2,50)
    print(a)
    space.extend(a)
    tickFeat.extend(result[0])
    plt.errorbar( a, result[1], result[2], fmt='o', label =model[1], color = color)
    count += 1

plt.xticks(space, tickFeat, rotation = 'vertical',  fontsize =12)
plt.ylim(.2, 1)
plt.legend()

plt.show()

In [ ]:
arr_diff_all = []

for m, m_key in zip (models, ml_dicts.keys()):
    acc_diff_arr = [] 
    sd_diff_arr = [] 
    for f_key in ml_dicts[m_key].keys():
        value = f_key.split(',')
        acc_diff_arr.append( ml_dicts[m_key][f_key][ 'tot_acc' ] - baseDict['lr']['lr, all'][ 'tot_acc' ]  )

        sd_train = jack_SD( baseDict['lr']['lr, all'][ 'jack_train' ], ml_dicts[m_key][f_key]['jack_train'] )[0]
        sd_test = jack_SD(  baseDict['lr']['lr, all'][ 'jack_test' ],  ml_dicts[m_key][f_key]['jack_test']   )[0]

        sd = np.sqrt( np.array((sd_train**2)) + np.array((sd_test**2)))
        sd_diff_arr.append(sd) # append sd_arr to an array
    arr_diff_all.append([ list(ml_dicts[m_key].keys()), acc_diff_arr, sd_diff_arr])

In [ ]:
colors = ['blue', 'purple', 'green', 'orange', 'red', 'brown']
plt.figure(figsize=(15, 7))
plt.title( "Precision  differences for ML methods versus LR_all for feature setsD", fontweight ='bold', fontsize =12)
plt.xlabel("Features", fontweight ='bold', fontsize =12)
plt.ylabel("Precision  difference", fontweight ='bold', fontsize =12)

count = 0
n = len(colors)-0.5
space = []
tickFeat = []

for result, model, color in zip(arr_diff_all, models, colors):
    a = np.linspace(n*count, n*(1+count)-2,50)
    space.extend(a)
    tickFeat.extend(result[0])
    plt.errorbar( a, result[1], result[2], fmt='o', label =model[1], color = color)
    count += 1
    
plt.plot(np.array(space), np.zeros(50*1), color = 'Black')        
plt.xticks(space, tickFeat, rotation = 'vertical',  fontsize =12)
plt.ylim(-.5, 1)
plt.legend()

plt.show()

In [ ]:
print(1)