# Tutorial 9: seq on all features (forward)

---

### Introduction

Hello, this notebook will show how to use sqe to perform further feature selection, as we found that most features are very highly correlated, therfore we would need to remove those using the tool that we mentioned above.

first, let us call the data

In [1]:
%store -r df_input_GS
%store -r y_GS
%store -r df_GS

In [2]:
y_GS = y_GS.map({'S': 1, 'B': 0})

---

calling some packages

In [3]:
# Python packages 
import pandas as pd # for importing data into data frame format
import seaborn as sns # For drawing useful graphs, such as bar graphs
import numpy as np
import matplotlib.pyplot as plt

---

<b><i> Data splitting </i></b>

In [4]:
from sklearn.model_selection import train_test_split

Xtrain_finall, Xtest_finall, Ytrain_finall, Ytest_finall = train_test_split( df_input_GS, y_GS, test_size = 0.3, random_state=3, stratify=y_GS) # train and valid sets

Xtrain, Xtest, Ytrain, Ytest = train_test_split( Xtrain_finall, Ytrain_finall, test_size = 0.3, random_state=3, stratify=Ytrain_finall) # train and valid sets

In [5]:
print(Xtrain.shape)
print(Xtest.shape)

(246, 2074)
(106, 2074)

---

<b><i> get the best N features </i></b>

In [6]:
%store -r featImp_GS

In [7]:
arrimp = np.array(featImp_GS).mean(0)
sorted_idx = arrimp.argsort()
print(sorted_idx[-10:])

[1793 1775 2048   31    3 1771  544 1781   17   45]

In [8]:
# cols_ordered = df_input_GS.columns[sorted_idx][-400:]
cols_ordered = df_input_GS.columns[sorted_idx]

cols_ordered

Index([2432.121, 1356.693, 2480.996, 2264.315, 1781.884,  2387.33, 2436.692,
       1391.648, 2455.152,  991.829,
       ...
       1968.596, 1942.053, 2441.281,   842.04,  834.451, 1936.251, 1010.382,
       1950.821,  838.229,  845.886],
      dtype='object', length=2074)

---

In [10]:
Xtrain[cols_ordered]

,2432.121,1356.693,2480.996,2264.315,1781.884,2387.330,2436.692,1391.648,2455.152,991.829,...,1968.596,1942.053,2441.281,842.040,834.451,1936.251,1010.382,1950.821,838.229,845.886
432,0.792975,1.242994,0.703734,0.990995,1.198615,0.835977,0.781998,1.230803,0.746577,1.169617,...,0.815382,0.764563,0.771690,1.109491,1.102894,0.760306,1.165852,0.780526,1.105202,1.112365
313,0.192169,0.752364,0.176871,0.333602,0.526052,0.223239,0.182105,0.510697,0.175116,1.027192,...,0.126603,0.093964,0.187895,1.098891,1.089806,0.089198,1.041778,0.103471,1.107623,1.099676
229,-0.049366,-0.688181,-0.027792,-0.222646,-0.471466,-0.080842,-0.051324,-0.433444,-0.016096,-0.840733,...,0.034246,0.081762,-0.059521,-0.841554,-0.853669,0.090944,-0.840174,0.065053,-0.848081,-0.843845
424,1.606836,1.617536,1.589289,1.655937,1.666038,1.612761,1.610847,1.599383,1.562510,1.493416,...,1.561311,1.538051,1.591920,1.375065,1.373744,1.534028,1.482971,1.545766,1.375364,1.380391
478,0.508995,-0.293093,0.470531,0.323130,0.024411,0.481035,0.527274,-0.012645,0.481485,-0.314105,...,0.530471,0.516423,0.508508,-0.195704,-0.180574,0.512587,-0.296909,0.522294,-0.181148,-0.191855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,0.248446,-0.071266,0.229865,0.150043,0.050956,0.227695,0.248362,0.108773,0.260749,-0.366056,...,0.396414,0.438002,0.266693,-0.574196,-0.581777,0.446361,-0.390573,0.422293,-0.576900,-0.576983
125,-1.056712,-0.271716,-1.085209,-0.891104,-0.597914,-1.019831,-1.061795,-0.591449,-1.085920,-0.428267,...,-1.072314,-1.105340,-1.066621,-0.779755,-0.787820,-1.108653,-0.479546,-1.096333,-0.782114,-0.780609
501,1.470237,0.048709,1.566631,0.996412,0.487898,1.323513,1.458622,0.462390,1.513831,-0.063827,...,1.560300,1.616648,1.496513,0.006132,0.017340,1.627461,-0.049297,1.602617,0.022853,0.011958
172,-0.385902,-0.486258,-0.369736,-0.424783,-0.457620,-0.391652,-0.385030,-0.464558,-0.358892,-0.635274,...,-0.364101,-0.339263,-0.372285,-0.792615,-0.805254,-0.334155,-0.652778,-0.347657,-0.796836,-0.792851
265,1.574866,1.380938,1.581815,1.550218,1.467564,1.592032,1.587682,1.417213,1.598900,1.330311,...,1.616505,1.625081,1.592172,1.301640,1.294190,1.622709,1.327060,1.620732,1.292952,1.304199

### SFS

In [11]:
# explore the number of selected features for RFE
from numpy import mean
from numpy import std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.pipeline import Pipeline
from matplotlib import pyplot
from sklearn.linear_model import LogisticRegression

In [ ]:
# https://machinelearningmastery.com/rfe-feature-selection-in-python/
selected = []
imp_ind = []
imp_freq = []

for i in range(1, 51, 1):
    print(i)
    sfs = SequentialFeatureSelector(estimator=LogisticRegression(solver = 'newton-cg'), n_features_to_select=i, direction = 'forward')
    # fit sfs
    sfs.fit(Xtrain[cols_ordered].values, Ytrain)
    # summarize all features
    selected_feat = []
    for i in range(Xtrain[cols_ordered].shape[1]):
        if sfs.support_[i] == True:
            selected_feat.append(i)
            print('Column: %d, Selected %s,' % (i, sfs.support_[i]))
        
    # print()
    selected.append(selected_feat)
    
    result = list(set(imp_ind) ^ set(selected[-1]))
    imp_freq.extend(Xtrain[cols_ordered].columns[result])    
    imp_ind.extend(result)    
    
    print(selected[-1])
    print(result)
    print(imp_ind)
    print(imp_freq)
    print()

1
Column: 506, Selected True,
[506]
[506]
[506]
[2485.753]

2
Column: 506, Selected True,
Column: 1153, Selected True,
[506, 1153]
[1153]
[506, 1153]
[2485.753, 1949.354]

3
Column: 78, Selected True,
Column: 506, Selected True,
Column: 1153, Selected True,
[78, 506, 1153]
[78]
[506, 1153, 78]
[2485.753, 1949.354, 2400.593]

4
Column: 78, Selected True,
Column: 265, Selected True,
Column: 506, Selected True,
Column: 1153, Selected True,
[78, 265, 506, 1153]
[265]
[506, 1153, 78, 265]
[2485.753, 1949.354, 2400.593, 1058.653]

5
Column: 78, Selected True,
Column: 265, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1153, Selected True,
[78, 265, 506, 900, 1153]
[900]
[506, 1153, 78, 265, 900]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729]

6
Column: 78, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1153, Selected True,
[78, 265, 276, 506, 900, 1153]
[276]
[506, 1153, 78, 265, 900, 276]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585]

7
Column: 78, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
[78, 265, 276, 506, 900, 1056, 1153]
[1056]
[506, 1153, 78, 265, 900, 276, 1056]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727]

8
Column: 78, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[78, 265, 276, 506, 900, 1056, 1153, 1805]
[1805]
[506, 1153, 78, 265, 900, 276, 1056, 1805]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393]

9
Column: 78, Selected True,
Column: 101, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[78, 101, 265, 276, 506, 900, 1056, 1153, 1805]
[101]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023]

10
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[17, 78, 101, 265, 276, 506, 900, 1056, 1153, 1805]
[17]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427]

11
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[126]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739]

12
Column: 0, Selected True,
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[0]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121]

13
Column: 0, Selected True,
Column: 2, Selected True,
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[2]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996]

14
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[3]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315]

15
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[5]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33]

16
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[6]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692]

17
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[10]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534]

18
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 15, Selected True,
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 15, 17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[15]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614]

19
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[13]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082]

20
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 16, 17, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[16]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13, 16]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082, 2191.581]

21
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 20, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 16, 17, 20, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[20]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13, 16, 20]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082, 2191.581, 2235.035]

22
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 19, Selected True,
Column: 20, Selected True,
Column: 25, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 16, 17, 19, 20, 25, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[25]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13, 16, 20, 19, 25]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082, 2191.581, 2235.035, 2165.948, 2219.726]

24
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 19, Selected True,
Column: 20, Selected True,
Column: 25, Selected True,
Column: 26, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 16, 17, 19, 20, 25, 26, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[26]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13, 16, 20, 19, 25, 26]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082, 2191.581, 2235.035, 2165.948, 2219.726, 1245.863]

25
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 19, Selected True,
Column: 20, Selected True,
Column: 25, Selected True,
Column: 26, Selected True,
Column: 32, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 16, 17, 19, 20, 25, 26, 32, 78, 101, 126, 265, 276, 506, 900, 1056, 1153, 1805]
[32]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13, 16, 20, 19, 25, 26, 32]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082, 2191.581, 2235.035, 2165.948, 2219.726, 1245.863, 1314.726]

26
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 19, Selected True,
Column: 20, Selected True,
Column: 25, Selected True,
Column: 26, Selected True,
Column: 32, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 264, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 16, 17, 19, 20, 25, 26, 32, 78, 101, 126, 264, 265, 276, 506, 900, 1056, 1153, 1805]
[264]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13, 16, 20, 19, 25, 26, 32, 264]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082, 2191.581, 2235.035, 2165.948, 2219.726, 1245.863, 1314.726, 1139.622]

27
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 19, Selected True,
Column: 20, Selected True,
Column: 25, Selected True,
Column: 26, Selected True,
Column: 32, Selected True,
Column: 77, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 264, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 16, 17, 19, 20, 25, 26, 32, 77, 78, 101, 126, 264, 265, 276, 506, 900, 1056, 1153, 1805]
[77]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13, 16, 20, 19, 25, 26, 32, 264, 77]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082, 2191.581, 2235.035, 2165.948, 2219.726, 1245.863, 1314.726, 1139.622, 1877.365]

28
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 19, Selected True,
Column: 20, Selected True,
Column: 25, Selected True,
Column: 26, Selected True,
Column: 32, Selected True,
Column: 77, Selected True,
Column: 78, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 264, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 706, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 16, 17, 19, 20, 25, 26, 32, 77, 78, 101, 126, 264, 265, 276, 506, 706, 900, 1056, 1153, 1805]
[706]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13, 16, 20, 19, 25, 26, 32, 264, 77, 706]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082, 2191.581, 2235.035, 2165.948, 2219.726, 1245.863, 1314.726, 1139.622, 1877.365, 2488.138]

29
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 19, Selected True,
Column: 20, Selected True,
Column: 25, Selected True,
Column: 26, Selected True,
Column: 32, Selected True,
Column: 77, Selected True,
Column: 78, Selected True,
Column: 86, Selected True,
Column: 101, Selected True,
Column: 126, Selected True,
Column: 264, Selected True,
Column: 265, Selected True,
Column: 276, Selected True,
Column: 506, Selected True,
Column: 706, Selected True,
Column: 900, Selected True,
Column: 1056, Selected True,
Column: 1153, Selected True,
Column: 1805, Selected True,
[0, 2, 3, 5, 6, 10, 13, 15, 16, 17, 19, 20, 25, 26, 32, 77, 78, 86, 101, 126, 264, 265, 276, 506, 706, 900, 1056, 1153, 1805]
[86]
[506, 1153, 78, 265, 900, 276, 1056, 1805, 101, 17, 126, 0, 2, 3, 5, 6, 10, 15, 13, 16, 20, 19, 25, 26, 32, 264, 77, 706, 86]
[2485.753, 1949.354, 2400.593, 1058.653, 1312.729, 1470.585, 2497.727, 1315.393, 1450.023, 1321.427, 1318.739, 2432.121, 2480.996, 2264.315, 2387.33, 2436.692, 1276.534, 1927.614, 1180.082, 2191.581, 2235.035, 2165.948, 2219.726, 1245.863, 1314.726, 1139.622, 1877.365, 2488.138, 2323.155]

30
Column: 0, Selected True,
Column: 2, Selected True,
Column: 3, Selected True,
Column: 5, Selected True,
Column: 6, Selected True,
Column: 10, Selected True,
Column: 13, Selected True,
Column: 15, Selected True,
Column: 16, Selected True,
Column: 17, Selected True,
Column: 19, Selected True,
Column: 20, Selected True,
Column: 25, Selected True,
Column: 26, Selected True,
Column: 32, Selected True,
Column: 77, Selected True,
Column: 78, Selected True,

---

In [ ]:
print(len(selected ))

print((selected ))
print(cols_ordered[-50:])
# selected.append(cols_ordered[-51:])
# selected.append(cols_ordered)

### LR

In [ ]:
lr = LogisticRegression()

In [ ]:
solvers = ['newton-cg', 'liblinear']
penalty = ['l2']
c_values = [1000, 100, 10, 1.0, 0.1, 0.01, 0.001]
lr_par = dict(solver=solvers,penalty=penalty,C=c_values)

In [ ]:
models = [[lr, 'lr', 14]]
par = [lr_par]

In [ ]:
from source.ml_acc import get_accuracy_ml

In [ ]:
num_ml_tools = len(par)
ml_dicts = {}

for m, par in zip(models, par):
    key0 = str(m[1])
    ml_dicts[key0] = {}
    for f in selected:
        print(cols_ordered[f])

        xtr =  Xtrain[cols_ordered].iloc[:, f]
        xte =  Xtest[cols_ordered].iloc[:, f]
        print(xtr)
        results = get_accuracy_ml (m[0], m[2], par, np.array(xtr), np.array(Ytrain), np.array(xte), np.array(Ytest)) # to get the accuracies for the ml model

        key = str(m[1])+","+str(len(f))
        ml_dicts[key0][key] = {}

        ml_dicts[key0][key]['tot_acc'] = results[0]
        ml_dicts[key0][key]['jack_train'] = results[1]
        ml_dicts[key0][key]['jack_test'] = results[2]

---

In [ ]:
import json

In [ ]:
with open('ml_gs_fs9.txt', 'w') as file:
     file.write(json.dumps(ml_dicts)) # use `json.loads` to do the reverse

In [ ]:
import json
with open('ml_gs_fs9.txt') as f:
    data = f.read()
    
ml_dicts = json.loads(data)

with open('base_gs.txt') as f:
    data = f.read()
    
baseDict = json.loads(data)
baseDict['lr'].keys()

In [ ]:
print(baseDict['lr'].keys()    )
print(ml_dicts['lr'].keys()    )

In [ ]:
from source.calculate_jack import jack_SD # importing the baseline code from source.basline file

In [ ]:
arr_all = []
for m, d in zip (models, ml_dicts.keys()):
    acc_arr = [] 
    sd_arr = [] 

    # print(ml_dicts[d])
    for key in ml_dicts[d].keys():
        acc_arr.append(ml_dicts[d][key][ 'tot_acc' ]) # append total accuracy to an array
        sd_train = jack_SD(np.zeros( len(ml_dicts[d][key][ 'jack_train' ]) ), ml_dicts[d][key][ 'jack_train' ])[0]
        sd_test = jack_SD(np.zeros( len(ml_dicts[d][key][ 'jack_test' ]) ), ml_dicts[d][key][ 'jack_test' ])[0]
        sd = np.sqrt( np.array((sd_train**2)) + np.array((sd_test**2)))
        sd_arr.append(sd) # append sd_arr to an array
    arr_all.append([ list(ml_dicts[d].keys()), acc_arr, sd_arr])

In [ ]:
colors = ['blue', 'purple', 'green', 'orange', 'red', 'brown']
plt.figure(figsize=(15, 7))
plt.title( "Precision  for different features with the SD", fontweight ='bold', fontsize =12)
plt.xlabel("Features", fontweight ='bold', fontsize =12)
plt.ylabel("Precision", fontweight ='bold', fontsize =12)

count = 0
n = len(colors)-1

space = []
tickFeat = []

for result, model, color in zip(arr_all, models, colors):
    a = np.linspace(n*count, n*(1+count)-2,50)
    print(a)
    space.extend(a)
    tickFeat.extend(result[0])
    plt.errorbar( a, result[1], result[2], fmt='o', label =model[1], color = color)
    count += 1

plt.xticks(space, tickFeat, rotation = 'vertical',  fontsize =12)
plt.ylim(.2, 1)
plt.legend()

plt.show()

In [ ]:
arr_diff_all = []

for m, m_key in zip (models, ml_dicts.keys()):
    acc_diff_arr = [] 
    sd_diff_arr = [] 
    for f_key in ml_dicts[m_key].keys():
        value = f_key.split(',')
        acc_diff_arr.append( ml_dicts[m_key][f_key][ 'tot_acc' ] - baseDict['lr']['lr, all'][ 'tot_acc' ]  )

        sd_train = jack_SD( baseDict['lr']['lr, all'][ 'jack_train' ], ml_dicts[m_key][f_key]['jack_train'] )[0]
        sd_test = jack_SD(  baseDict['lr']['lr, all'][ 'jack_test' ],  ml_dicts[m_key][f_key]['jack_test']   )[0]

        sd = np.sqrt( np.array((sd_train**2)) + np.array((sd_test**2)))
        sd_diff_arr.append(sd) # append sd_arr to an array
    arr_diff_all.append([ list(ml_dicts[m_key].keys()), acc_diff_arr, sd_diff_arr])

In [ ]:
colors = ['blue', 'purple', 'green', 'orange', 'red', 'brown']
plt.figure(figsize=(15, 7))
plt.title( "Precision  differences for ML methods versus LR_all for feature setsD", fontweight ='bold', fontsize =12)
plt.xlabel("Features", fontweight ='bold', fontsize =12)
plt.ylabel("Precision  difference", fontweight ='bold', fontsize =12)

count = 0
n = len(colors)-0.5
space = []
tickFeat = []

for result, model, color in zip(arr_diff_all, models, colors):
    a = np.linspace(n*count, n*(1+count)-2,50)
    space.extend(a)
    tickFeat.extend(result[0])
    plt.errorbar( a, result[1], result[2], fmt='o', label =model[1], color = color)
    count += 1
    
plt.plot(np.array(space), np.zeros(50*1), color = 'Black')        
plt.xticks(space, tickFeat, rotation = 'vertical',  fontsize =12)
plt.ylim(-.5, 1)
plt.legend()

plt.show()